### PR TITLE
Adds 'Evidence' to the prompt output.

### PR DESCRIPTION
**Pull request by wilkie**
Simply adds the 'Evidence' column and fills it with the AI response if it exists or fills it in with a blank string.

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
please make sure ./bin/test.sh is passing locally before merging, since that's not running on our PRs right now

**Comment by wilkie** [comment]
> please make sure ./bin/test.sh is passing locally before merging, since that's not running on our PRs right now

I did do that locally and it actually is running on our PRs! @davidsbailey  Can you see this link?

image

**Comment by wilkie** [comment]
```
[Container] 2024/03/08 18:04:28.110688 Running command ./ci-test.sh
--
396 | Testing Docker Image aiproxy:39fd93d...
397 | ============================= test session starts ==============================
398 | platform linux -- Python 3.11.8, pytest-7.4.3, pluggy-1.4.0
399 | rootdir: /app
400 | plugins: requests-mock-1.11.0, mock-3.12.0
401 | collected 118 items
402 |  
403 | tests/accuracy/test_accuracy.py s                                        [  0%]
404 | tests/routes/test_assessment_routes.py .......................           [ 20%]
405 | tests/routes/test_openai_routes.py .....                                 [ 24%]
406 | tests/routes/test_simple_routes.py .....                                 [ 28%]
407 | tests/unit/assessment/test_assess.py ..                                  [ 30%]
408 | tests/unit/assessment/test_assessment.py .....                           [ 34%]
409 | tests/unit/assessment/test_code_feature_extractor.py .                   [ 35%]
410 | tests/unit/assessment/test_label.py .................................... [ 66%]
411 | ........                                                                 [ 72%]
412 | tests/unit/assessment/test_report.py ................                    [ 86%]
413 | tests/unit/assessment/test_rubric_tester.py ................             [100%]
414 |  
415 | ======================== 117 passed, 1 skipped in 2.15s ========================
416 | Name                                                   Stmts   Miss  Cover   Missing
417 | ------------------------------------------------------------------------------------
418 | lib/__init__.py                                            0      0   100%
419 | lib/assessment/__init__.py                                 0      0   100%
420 | lib/assessment/assess.py                                  33      1    97%   57
421 | lib/assessment/code_feature_extractor.py                  49     10    80%   35-46
422 | lib/assessment/config.py                                   6      0   100%
423 | lib/assessment/decision_trees.py                          15      2    87%   18, 26
424 | lib/assessment/label.py                                  276     46    83%   84-89, 92-115, 124-148, 160-166, 316, 327, 351, 360, 367-368, 373-375
425 | lib/assessment/report.py                                 122      1    99%   57
426 | lib/assessment/rubric_tester.py                          283    184    35%   45-92, 112-124, 127-141, 160-164, 182-190, 211-245, 269-274, 280-407, 410-415
427 | src/__init__.py                                           28      0   100%
428 | src/assessment.py                                        115     47    59%   54-57, 136-175, 180-216
429 | src/openai.py                                             16      0   100%
430 | src/test.py                                               20      0   100%
431 | tests/accuracy/conftest.py                                 0      0   100%
432 | tests/accuracy/test_accuracy.py                           13      4    69%   16-19
433 | tests/conftest.py                                         37      1    97%   53
434 | tests/routes/conftest.py                                   4      0   100%
435 | tests/routes/test_assessment_routes.py                   131      0   100%
436 | tests/routes/test_openai_routes.py                        38      0   100%
437 | tests/routes/test_simple_routes.py                        17      0   100%
438 | tests/unit/assessment/conftest.py                        125      8    94%   82-93
439 | tests/unit/assessment/test_assess.py                      14      0   100%
440 | tests/unit/assessment/test_assessment.py                  40      0   100%
441 | tests/unit/assessment/test_code_feature_extractor.py      12      0   100%
442 | tests/unit/assessment/test_label.py                      336      0   100%
443 | tests/unit/assessment/test_report.py                     155      0   100%
444 | tests/unit/assessment/test_rubric_tester.py              181      0   100%
445 | tests/unit/conftest.py                                     4      0   100%
446 | ------------------------------------------------------------------------------------
447 | TOTAL                                                   2070    304    85%
448 |  
449 | [Container] 2024/03/08 18:04:32.907478 Phase complete: BUILD State: SUCCEEDED
450 | [Container] 2024/03/08 18:04:32.907496 Phase context status code:  Message:
451 | [Container] 2024/03/08 18:04:32.939504 Entering phase POST_BUILD
452 | [Container] 2024/03/08 18:04:32.941545 Phase complete: POST_BUILD State: SUCCEEDED
```

**Comment by davidsbailey** [comment]
> > please make sure ./bin/test.sh is passing locally before merging, since that's not running on our PRs right now
> 
> I did do that locally and it actually is running on our PRs! Can you see this link?
> 
> image

oh wait what? Yes, I can see that, apologies I did not look for it! 

Does this mean we can close out https://codedotorg.atlassian.net/browse/AITT-428 ?

**Comment by wilkie** [comment]
I have no problem closing that out. Only had it left open as blocked since Infra has further work there and I didn't want to lose following up on it.

**Comment by davidsbailey** [comment]
> I have no problem closing that out. Only had it left open as blocked since Infra has further work there and I didn't want to lose following up on it.

oh I see, they want to turn it into "infra as code" so the config change is not lost. this makes sense to keep open then I think

**Pull request merged**
