### PR TITLE
Scale AIProxy ECS Service

### PR DESCRIPTION
**Pull request by cat5inthecradle**
Scale the AIProxy ECS Service based on resource usage.

### Testing Strategy

1. [DONE] Manually deploy the updates to the cicd-dependencies stack to create the necessary autoscaling role.
2. [DONE] Deploy a [development environment](https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/aiproxy-scale-ecs-cicd/view?region=us-east-1) with this branch to confirm valid configuration and [experiment with scaling](https://codedotorg.slack.com/archives/C050HE4QDHR/p1704907046776039).

### Deployment Strategy

1. Manually deploy the updates to the cicd-dependencies stack, careful to check for drift first.
2. Merge to automatically deploy autoscaling implementation.

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
I'm noticing that codebuild ci steps aren't running... I'll investigate that.

**Comment by tess323** [comment]
@wilkie @davidsbailey tagging for review based on Darin's comment here: https://codedotorg.slack.com/archives/C050HE4QDHR/p1705423583338439?thread_ts=1705418213.116809&cid=C050HE4QDHR

**Review by davidsbailey — COMMENTED** [review]
Thanks for including us on the review. I'm not fluent in AWS config and do not have any input here unfortunately.

**Comment by cat5inthecradle** [comment]
Using admin powers to merge. I'll be monitoring this over the weekend and into Morning.

**Pull request merged**
